version: '3.8'

services:
  zabbix-glpi-reporter:
    image: ghcr.io/tiagopatriarca/zabbix_glpi_report:latest
    container_name: relatorio_zabbix_glpi
    ports:
      - "8501:8501"
    volumes:
      # Mapeia uma pasta inteira de dados para garantir que o Docker não crie como diretório o arquivo config.json
      - ./data:/app/data
    restart: unless-stopped
