version: '3.8'

services:
  zabbix-glpi-reporter:
    image: ghcr.io/tiagopatriarca/zabbix_glpi_report:latest
    container_name: relatorio_zabbix_glpi
    ports:
      - "8501:8501"
    volumes:
      # Usando Named Volume gerenciado pelo Docker (muito mais seguro contra erros de permissão em hospedagens)
      - app_data:/app/data
    restart: unless-stopped

volumes:
  app_data:
